#ifndef __MOS_INTERFACE_GPU_WRAPPER_DEFS_H__
#define __MOS_INTERFACE_GPU_WRAPPER_DEFS_H__

typedef enum _GpuWrapperComponentFuncType
{
    GPU_WRAPPER_FUNC_TYPE_DECODE,
    GPU_WRAPPER_FUNC_TYPE_ENCODE,
    GPU_WRAPPER_FUNC_TYPE_VP_COMPUTE,
    GPU_WRAPPER_FUNC_TYPE_VP_VEBOX,
    GPU_WRAPPER_FUNC_TYPE_RENDER,
    GPU_WRAPPER_FUNC_TYPE_INVALID
} GpuWrapperComponentFuncType;

#endif // __MOS_INTERFACE_GPU_WRAPPER_DEFS_H__
